apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-mlops
  labels:
    app: cats-dogs-mlops
spec:
  type: LoadBalancer
  selector:
    app: cats-dogs-mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
